### ISSUE TITLE
Migrate to Hugo + Structure for redesign

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/roxanarobinson.com#4]
- [x] Clear out all the contents of the Master branch (I've already deployed the archive-jekyll branch to the currently live site)
- [x] Move content into Hugo-style folders (can leave content from current master, but restructured) (e.g. move `_posts` to `content/posts`
- [x] Add Hugo [Starter](https://github.com/theNewDynamic/hugo-starter) files into master
- [x] Add base component (as in bottom of directions for starter)
- [x] Add [event](https://github.com/theNewDynamic/hugo-layout_module-events) component and [books](https://github.com/theNewDynamic/hugo-layout_module-books) component
- [x] Make sure site just runs

**Comment by AdamChlan** [comment]
@budparr  I think I may need permission to push to this repo. Also, I had started this on a "hugo-migration" branch, but are you wanting me to do this directly on Master?

**Comment by budparr** [comment]
you should have write access. this branch is fine, thank you.

**Comment by budparr** [comment]
@AdamChlan just checking to see if you're getting access

**Comment by AdamChlan** [comment]
@budparr yes, all good.

**Comment by AdamChlan** [comment]
@budparr the site does "just run" but curious if you want me to take it further for you.

**Comment by budparr** [comment]
I'll give it a looksee first.

**Comment by AdamChlan** [comment]
hug-migration branch
