### ISSUE TITLE
Create Media and Writing Pages

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/roxanarobinson.com#7]
As discussed

**Comment by regisphilibert** [comment]
Alright, it's a WIP as to styling but at least the general data/markup is there. 

- I reverted from `hugo54`to `hugo` as the `package.json`
- I used the list script from the Jekyll site as is.

Do you want me to spend some time plussing it stylewise, or do you have some ideas / rework planned in your head? I just want to make I don't diverge from your original ideas for this page and you have to redo it.

**Comment by budparr** [comment]
Looks good
 I'll style it
